import { Link } from 'react-router-dom'
import { PlayerAvatar } from './PlayerAvatar'

type Direction = 'over' | 'under'
type SuggestionItem = {
  type: string
  marketLine?: number
  fairLine?: number
  confidence?: number
  rationale?: string[] | string
  chosenDirection?: Direction
  betterDirection?: Direction
  suggestion?: string
  playerId?: number
  player_id?: number
  playerName?: string
  player_name?: string
  hitRate?: number
  sampleSize?: number
  tier?: 'lock' | 'strong' | 'lean'
  streak?: number
  consistency?: number
  /** Opponent team abbr (e.g. BOS) for matchup context — API may send opponent_abbr (snake_case) */
  opponentAbbr?: string
  opponent_abbr?: string
  /** Opponent def rank for this stat type (1=best D). Helps decide if matchup is tough. */
  opponentDefRank?: number
  /** When set (e.g. "ml_blended"), confidence used ML model — AI was used */
  confidenceSource?: string
  /** When "llm", rationale was generated by LLM — AI was used */
  rationaleSource?: string
  /** When true, ML model contributed to this suggestion */
  mlAvailable?: boolean
  /** Game date YYYY-MM-DD for bet payload */
  gameDate?: string
  game_date?: string
  /** Insight engine: matchup strength 0–100 */
  matchup_score?: number | null
  /** Insight category (e.g. favorable_scoring_matchup, hot_streak) */
  insight_type?: string | null
  /** Short narrative for matchup (from backend) */
  matchup_explanation?: string | null
  /** Opponent def rank vs position (e.g. "#3 most PTS to PGs") */
  opponent_def_rank_vs_position?: string | null
  /** Supporting metrics (recent_avg_5, pace, usage_approx) */
  supporting_metrics?: Record<string, unknown> | null
  /** Backend hot-form filter: player recent &gt; season avg */
  isHot?: boolean
  /** 0-1 upward trend in recent games */
  heat_index?: number
  /** 0-1 volatility (CV) over recent games */
  volatility_index?: number
  /** Synced sportsbook lines from The Odds API */
  liveOdds?: {
    byBook?: Record<string, { line?: number; over?: number; under?: number }>
    bestLine?: { over?: number; under?: number }
    source?: string
  }
  lineSource?: string
}

/** API often returns snake_case; SuggestionItem supports both. Pick of the day is the same shape. */
export type PickOfTheDay = SuggestionItem

export type { SuggestionItem }

const TIER_STYLES: Record<string, { bg: string; text: string; label: string }> = {
  lock: { bg: 'bg-primary-container', text: 'text-white', label: 'LOCK' },
  strong: { bg: 'bg-betting-green', text: 'text-white', label: 'STRONG' },
  lean: { bg: 'bg-secondary-container', text: 'text-white', label: 'LEAN' },
}

function TierBadge({ tier }: { tier?: string }) {
  if (!tier) return null
  const style = TIER_STYLES[tier]
  if (!style) return null
  return (
    <span className={`${style.bg} ${style.text} text-[9px] font-extrabold px-1.5 py-0.5 rounded tracking-wider shadow-sm`}>
      {style.label}
    </span>
  )
}

type SuggestionCardsProps = {
  suggestions: SuggestionItem[]
  horizontal?: boolean
  onAddToTracker?: (s: SuggestionItem) => void
  isAddingToTracker?: boolean
}

export function SuggestionCards({ suggestions, horizontal = false, onAddToTracker, isAddingToTracker }: SuggestionCardsProps) {
  const CardContent = ({ s }: { s: SuggestionItem }) => {
    const direction = s.suggestion || s.chosenDirection || ((s.fairLine != null && s.marketLine != null && s.fairLine >= s.marketLine) ? 'over' : 'under')
    const isOver = direction === 'over'
    // Prefer LLM rationale when present: API sends [summary, llm] so use last element
    const rationaleText = Array.isArray(s.rationale)
      ? (s.rationale.length > 1 ? s.rationale[s.rationale.length - 1] : s.rationale[0])
      : (s.rationale || '')

    return (
      <>
        {/* Header: tier + type + AI indicator + direction */}
        <div className="flex items-center justify-between gap-1 mb-1.5">
          <div className="flex items-center gap-1.5 min-w-0 flex-1">
            <TierBadge tier={s.tier} />
            <strong className="text-xs font-bold text-on-surface truncate transition-colors duration-200">{s.type}</strong>
            {(s.confidenceSource === 'ml_blended' || s.rationaleSource === 'llm' || s.mlAvailable) && (
              <span className="flex-shrink-0 text-[9px] px-1.5 py-0.5 rounded bg-violet-100 dark:bg-violet-900/40 text-violet-700 dark:text-violet-300 font-medium" title="AI-enhanced (ML or LLM)">AI</span>
            )}
            {(s.matchup_score != null || s.matchup_explanation) && (
              <span className="flex-shrink-0 text-[9px] px-1.5 py-0.5 rounded bg-amber-100 dark:bg-amber-900/40 text-amber-800 dark:text-amber-200 font-medium" title="Matchup insight">Matchup</span>
            )}
            {s.heat_index != null && s.heat_index > 0.55 && (
              <span className="flex-shrink-0 text-[9px] px-1.5 py-0.5 rounded bg-orange-100 dark:bg-orange-900/40 text-orange-800 dark:text-orange-200 font-medium" title="Heating up">Heat</span>
            )}
            {s.volatility_index != null && s.volatility_index > 0.3 && (
              <span className="flex-shrink-0 text-[9px] px-1.5 py-0.5 rounded bg-surface-container-high text-on-surface-variant font-medium" title="High variance">Vol</span>
            )}
          </div>
          <span
            className={`text-[10px] px-1.5 py-0.5 rounded text-white font-semibold whitespace-nowrap ${isOver ? 'bg-betting-green' : 'bg-error'}`}
          >
            {isOver ? 'OVER' : 'UNDER'}
          </span>
        </div>

        {/* Player name + headshot */}
        {s.playerId && s.playerName && (
          <div className="mb-1.5 flex items-center gap-1.5 flex-wrap">
            <PlayerAvatar playerId={s.playerId} playerName={s.playerName} size="small" className="border border-outline/30" />
            <Link
              to={`/player/${s.playerId}`}
              className="text-[11px] text-primary-container hover:text-blue-800 dark:hover:text-blue-300 truncate transition-colors duration-200 hover:underline"
              title={s.playerName}
            >
              {s.playerName}
            </Link>
            {(s.opponentAbbr ?? s.opponent_abbr ?? s.opponentDefRank != null) && (
              <span className="text-[9px] text-on-surface-variant font-medium whitespace-nowrap" title="Opponent defense rank (lower = tougher)">
                {(s.opponent_abbr ?? s.opponentAbbr) && `vs ${s.opponent_abbr ?? s.opponentAbbr}`}
                {s.opponentDefRank != null && ` · Def #${s.opponentDefRank}`}
              </span>
            )}
          </div>
        )}

        {/* Stats grid */}
        <div className="space-y-0.5 text-[10px] text-on-surface-variant transition-colors duration-200">
          {s.marketLine != null && (
            <div className="flex justify-between items-center gap-1">
              <span className="text-on-surface-variant shrink-0">{s.type} line:</span>
              <span className="font-bold text-on-surface text-right flex flex-wrap items-center justify-end gap-1">
                {typeof s.marketLine === 'number' ? (Number.isInteger(s.marketLine) ? s.marketLine : s.marketLine.toFixed(1)) : s.marketLine}
                {s.lineSource === 'live_odds' && (
                  <span className="text-[8px] font-bold px-1 py-0.5 rounded bg-betting-green/15 text-betting-green border border-betting-green/25">LIVE</span>
                )}
              </span>
            </div>
          )}
          {s.lineSource === 'live_odds' && s.fairLine != null && s.marketLine != null && s.fairLine !== s.marketLine && (
            <div className="flex justify-between items-center text-[9px] text-on-surface-variant">
              <span>vs fair</span>
              <span className={s.fairLine > s.marketLine ? 'text-betting-green font-semibold' : 'text-error font-semibold'}>
                fair {typeof s.fairLine === 'number' ? s.fairLine.toFixed(1) : s.fairLine}
              </span>
            </div>
          )}
          {s.confidence != null && (
            <div className="flex justify-between items-center">
              <span className="text-on-surface-variant">Conf:</span>
              <span className="font-bold text-primary-container">{Math.round(s.confidence > 1 ? s.confidence : s.confidence * 100)}%</span>
            </div>
          )}
          {s.hitRate != null && (
            <div className={`flex justify-between items-center ${s.hitRate >= 75 ? 'text-betting-green' : s.hitRate >= 65 ? 'text-primary-container' : ''}`}>
              <span>Hit Rate:</span>
              <span className="font-bold">{typeof s.hitRate === 'number' && s.hitRate <= 1 ? (s.hitRate * 100).toFixed(0) : s.hitRate?.toFixed?.(0) ?? s.hitRate}%</span>
            </div>
          )}
          {typeof s.streak === 'number' && s.streak >= 3 && (
            <div className="flex justify-between items-center text-amber-600 dark:text-amber-400">
              <span>Streak:</span>
              <span className="font-bold">{s.streak} games</span>
            </div>
          )}
          {typeof s.consistency === 'number' && s.consistency > 0 && (
            <div className="flex justify-between items-center">
              <span className="text-on-surface-variant">Consist:</span>
              <span className="font-semibold">{(s.consistency * 100).toFixed(0)}%</span>
            </div>
          )}
        </div>

        {/* Matchup explanation (insight engine) */}
        {s.matchup_explanation && (
          <div className="mt-1.5 p-1.5 bg-amber-50 dark:bg-amber-900/20 rounded border border-amber-200 dark:border-amber-800/50 transition-colors duration-200">
            <p className="text-[9px] text-amber-900 dark:text-amber-200 line-clamp-3">{s.matchup_explanation}</p>
            {s.playerId && (
              <Link
                to={`/player/${s.playerId}`}
                className="mt-1 inline-block text-[9px] font-semibold text-amber-700 dark:text-amber-300 hover:underline"
              >
                View matchup →
              </Link>
            )}
          </div>
        )}

        {/* Rationale */}
        {rationaleText && (
          <div className="mt-2 p-1.5 bg-surface-container-low rounded border border-outline/20 transition-colors duration-200">
            <div className="flex flex-wrap gap-1 items-center">
              {(() => {
                const trendMatch = rationaleText.match(/\b(Up|Down|Flat)\s+form/i)
                const hitRateMatch = rationaleText.match(/(\d+(?:\.\d+)?)%\s+hit/i)
                const streakMatch = rationaleText.match(/(\d+)-game streak/i)
                const consistMatch = rationaleText.match(/very consistent|consistent/i)
                return (
                  <>
                    {trendMatch && (
                      <span className={`inline-flex items-center gap-0.5 px-1.5 py-0.5 rounded text-[9px] font-semibold ${
                        trendMatch[1].toLowerCase() === 'up' ? 'bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-300' :
                        trendMatch[1].toLowerCase() === 'down' ? 'bg-red-100 dark:bg-red-900/30 text-red-800 dark:text-red-300' :
                        'bg-yellow-100 dark:bg-yellow-900/30 text-yellow-800 dark:text-yellow-300'
                      }`}>
                        {trendMatch[1] === 'Up' ? '↑' : trendMatch[1] === 'Down' ? '↓' : '→'} {trendMatch[1]}
                      </span>
                    )}
                    {hitRateMatch && (
                      <span className={`inline-flex items-center px-1.5 py-0.5 rounded text-[9px] font-bold ${
                        parseFloat(hitRateMatch[1]) >= 75 ? 'bg-blue-100 dark:bg-blue-900/30 text-blue-800 dark:text-blue-300' :
                        'bg-surface-container-high text-on-surface-variant'
                      }`}>
                        {hitRateMatch[1]}%
                      </span>
                    )}
                    {streakMatch && (
                      <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[9px] font-bold bg-amber-100 dark:bg-amber-900/30 text-amber-800 dark:text-amber-300">
                        {streakMatch[1]}x
                      </span>
                    )}
                    {consistMatch && (
                      <span className="inline-flex items-center px-1.5 py-0.5 rounded text-[9px] font-semibold bg-purple-100 dark:bg-purple-900/30 text-purple-800 dark:text-purple-300">
                        {consistMatch[0]}
                      </span>
                    )}
                    {!trendMatch && !hitRateMatch && (
                      <span className="text-[9px] text-on-surface-variant line-clamp-2">{rationaleText}</span>
                    )}
                  </>
                )
              })()}
            </div>
          </div>
        )}

        {/* Add to Bet Tracker — show when callback provided and card has type + line (parent supplies player when needed) */}
        {onAddToTracker && s.type && (s.marketLine != null || s.fairLine != null) && (
          <div className="mt-2">
            <button
              type="button"
              onClick={(e) => { e.preventDefault(); e.stopPropagation(); onAddToTracker(s) }}
              disabled={isAddingToTracker}
              className="w-full py-1.5 px-2 rounded-md text-[10px] font-semibold bg-emerald-600 hover:bg-emerald-700 disabled:opacity-60 disabled:cursor-not-allowed text-white transition-colors dark:bg-betting-green dark:hover:bg-emerald-400 dark:text-white focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-emerald-500 flex items-center justify-center gap-1"
            >
              {isAddingToTracker ? (
                <>
                  <svg className="animate-spin h-3 w-3" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"><circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" /><path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z" /></svg>
                  Adding…
                </>
              ) : (
                <>
                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" /></svg>
                  Add to tracker
                </>
              )}
            </button>
          </div>
        )}
      </>
    )
  }

  if (horizontal) {
    return (
      <div className="w-full max-w-full overflow-x-auto overflow-y-visible -mx-2.5 px-2.5 pb-2 scrollbar-thin scrollbar-thumb-gray-300 scrollbar-track-gray-100" style={{ scrollbarWidth: 'thin' }}>
        <div className="flex gap-2.5 min-w-max">
          {suggestions.map((s: SuggestionItem, idx: number) => (
            <div
              key={`${s.playerId ?? s.player_id ?? 'p'}-${s.type ?? 'prop'}-${idx}`}
              className="flex-none w-48 sm:w-56 p-2.5 sm:p-3 border border-outline/20 rounded-lg bg-surface-container shadow-sm hover:shadow-md transition-all duration-200"
            >
              <CardContent s={s} />
            </div>
          ))}
        </div>
      </div>
    )
  }

  return (
    <div className="w-full">
      <div className="grid grid-cols-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-6 xl:grid-cols-8 2xl:grid-cols-10 gap-2 md:gap-3">
        {suggestions.map((s: SuggestionItem, idx: number) => (
          <div key={idx} className="p-2.5 sm:p-3 border border-outline/20 rounded-lg bg-surface-container shadow-sm hover:shadow-md transition-all duration-200">
            <CardContent s={s} />
          </div>
        ))}
      </div>
    </div>
  )
}
